service: Todoer

provider:
  name: aws
  runtime: nodejs12.x
  profile: streaming_devops_svc
  stage: ${opt:stage, 'staging'}
  environment:
    TABLE_NAME: TodoDbTable
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - dynamodb:Query
        - dynamodb:Scan
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
      Resource: 
        Fn::GetAtt:
          - TodoDbTable
          - Arn

functions:
  - AddTodoFn:
      handler: ./functions/add.handler
      events:
      - http:
          path: todo
          method: post
          cors: true
  - ListTodoFn:
      handler: ./functions/fetch.handler
      events:
      - http:
          path: todo
          method: get
          cors: true
  - UpdateTodoFn:
      handler: ./functions/update.handler
      events:
      - http:
          path: todo
          method: put
          cors: true

resources:
  Resources:
    TodoDbTable:
      Type: 'AWS::DynamoDB::Table'
      DeletionPolicy: Retain
      Properties:
        AttributeDefinitions:
          - AttributeName: "appId"
            AttributeType: "S"
          - AttributeName: "entityId"
            AttributeType: "S"
        KeySchema:
          - AttributeName: "appId"
            KeyType: "HASH"
          - AttributeName: "entityId"
            KeyType: "RANGE"
        ProvisionedThroughput:
          ReadCapacityUnits: 5
          WriteCapacityUnits: 5
        TableName: ${self:provider.environment.TABLE_NAME}

